-- SQL Script to Create All Tables for Your Application (PostgreSQL)
--
-- This script includes:
-- 1. ASP.NET Core Identity Tables (standard schema)
-- 2. Your custom LookupValues table
-- 3. Your custom Tickets table
-- 4. Your custom Comments table
--
-- Run this script in its entirety.

-- Ensure you are in the correct database schema (e.g., 'public')
-- SET search_path TO public;


-- -----------------------------------------------------
-- 1. Create LookupValues Table (Reference Data)
--    This should be created first as other tables depend on it.
-- -----------------------------------------------------
CREATE TABLE LookupValues (
    "Id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "CategoryType" VARCHAR(50) NOT NULL,
    "Code" VARCHAR(50) NOT NULL,
    "DisplayName" VARCHAR(100) NOT NULL,
    "SortOrder" INT,
    "IsActive" BOOLEAN DEFAULT TRUE NOT NULL,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Add a unique constraint to ensure 'Code' is unique within each 'CategoryType'
CREATE UNIQUE INDEX IX_LookupValues_CategoryType_Code ON LookupValues ("CategoryType", "Code");


-- -----------------------------------------------------
-- 2. Create ASP.NET Core Identity Tables
--    These are standard tables generated by IdentityDbContext.
--    Note: Column names are case-sensitive in PostgreSQL by default if quoted.
--    EF Core typically quotes them, so matching that helps.
-- -----------------------------------------------------

CREATE TABLE "AspNetUsers" (
    "Id" VARCHAR(450) PRIMARY KEY,
    "UserName" VARCHAR(256) NULL,
    "NormalizedUserName" VARCHAR(256) NULL,
    "Email" VARCHAR(256) NULL,
    "NormalizedEmail" VARCHAR(256) NULL,
    "EmailConfirmed" BOOLEAN NOT NULL,
    "PasswordHash" TEXT NULL,
    "SecurityStamp" TEXT NULL,
    "ConcurrencyStamp" TEXT NULL,
    "PhoneNumber" TEXT NULL,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL,
    "TwoFactorEnabled" BOOLEAN NOT NULL,
    "LockoutEnd" TIMESTAMP WITH TIME ZONE NULL,
    "LockoutEnabled" BOOLEAN NOT NULL,
    "AccessFailedCount" INT NOT NULL,

    -- Your Custom User Properties
    "FirstName" VARCHAR(100) NOT NULL DEFAULT '',
    "LastName" VARCHAR(100) NOT NULL DEFAULT '',
    "Avatar" VARCHAR(10) NOT NULL DEFAULT '',
    "RoleId" INT NOT NULL, -- Foreign key to LookupValues for user roles
    "CompletedTasks" INT NOT NULL DEFAULT 0,
    "TotalPoints" INT NOT NULL DEFAULT 0,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- Add a foreign key to LookupValues for RoleId
    CONSTRAINT "FK_AspNetUsers_LookupValues_RoleId" FOREIGN KEY ("RoleId") REFERENCES LookupValues ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE TABLE "AspNetRoles" (
    "Id" VARCHAR(450) PRIMARY KEY,
    "Name" VARCHAR(256) NULL,
    "NormalizedName" VARCHAR(256) NULL,
    "ConcurrencyStamp" TEXT NULL
);

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE TABLE "AspNetUserClaims" (
    "Id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "UserId" VARCHAR(450) NOT NULL,
    "ClaimType" TEXT NULL,
    "ClaimValue" TEXT NULL,
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" VARCHAR(128) NOT NULL,
    "ProviderKey" VARCHAR(128) NOT NULL,
    "ProviderDisplayName" TEXT NULL,
    "UserId" VARCHAR(450) NOT NULL,
    PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE TABLE "AspNetUserRoles" (
    "UserId" VARCHAR(450) NOT NULL,
    "RoleId" VARCHAR(450) NOT NULL,
    PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE TABLE "AspNetUserTokens" (
    "UserId" VARCHAR(450) NOT NULL,
    "LoginProvider" VARCHAR(128) NOT NULL,
    "Name" VARCHAR(128) NOT NULL,
    "Value" TEXT NULL,
    PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "RoleId" VARCHAR(450) NOT NULL,
    "ClaimType" TEXT NULL,
    "ClaimValue" TEXT NULL,
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


-- -----------------------------------------------------
-- 3. Create Tickets Table
-- -----------------------------------------------------
CREATE TABLE Tickets (
    "Id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Title" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(1000) NULL,
    "AssigneeId" VARCHAR(450) NOT NULL,
    "CreatedById" VARCHAR(450) NOT NULL,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "DueDate" TIMESTAMP WITHOUT TIME ZONE NULL,
    "PriorityId" INT NOT NULL, -- FK to LookupValues for TicketPriority
    "CategoryId" INT NOT NULL, -- FK to LookupValues for TicketCategory
    "StatusId" INT NOT NULL,   -- FK to LookupValues for TicketStatus
    "PhotoUrl" VARCHAR(500) NULL,
    "CompletedAt" TIMESTAMP WITHOUT TIME ZONE NULL,
    "ApprovedAt" TIMESTAMP WITHOUT TIME ZONE NULL,

    CONSTRAINT "FK_Tickets_AspNetUsers_AssigneeId" FOREIGN KEY ("AssigneeId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Tickets_AspNetUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Tickets_LookupValues_PriorityId" FOREIGN KEY ("PriorityId") REFERENCES LookupValues ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Tickets_LookupValues_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES LookupValues ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Tickets_LookupValues_StatusId" FOREIGN KEY ("StatusId") REFERENCES LookupValues ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Tickets_AssigneeId" ON Tickets ("AssigneeId");
CREATE INDEX "IX_Tickets_CreatedById" ON Tickets ("CreatedById");
CREATE INDEX "IX_Tickets_PriorityId" ON Tickets ("PriorityId");
CREATE INDEX "IX_Tickets_CategoryId" ON Tickets ("CategoryId");
CREATE INDEX "IX_Tickets_StatusId" ON Tickets ("StatusId");


-- -----------------------------------------------------
-- 4. Create Comments Table
-- -----------------------------------------------------
CREATE TABLE Comments (
    "Id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Content" VARCHAR(1000) NOT NULL,
    "UserId" VARCHAR(450) NOT NULL,
    "TicketId" INT NOT NULL,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT "FK_Comments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Comments_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES Tickets ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Comments_UserId" ON Comments ("UserId");
CREATE INDEX "IX_Comments_TicketId" ON Comments ("TicketId");